services:
  db:
    image: postgres:16
    container_name: sisas_db
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - sisas_pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sisas_backend
    env_file:
      - .env.prod
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: sisas_web
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backup:
    image: postgres:16
    container_name: sisas_backup
    env_file:
      - .env.prod
    environment:
      PGPASSWORD: ${DB_PASS}
    volumes:
      - ./backups:/backups
    depends_on:
      - db
    entrypoint: ["/bin/sh","-c"]
    command: >
      "chmod +x /backups/backup.sh &&
       while true; do
         /backups/backup.sh;
         sleep 86400;
       done"

volumes:
  sisas_pgdata:
